version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teddy-nest
    ports:
      - "3001:3001"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:16
    container_name: teddy-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: teddy
    ports:
      - "5432:5432"
